Nov 01 10:29:01 prospector python[1437238]: [2024-11-01 10:29:01,962: INFO/MainProcess] Task prospector.apps.crm.tasks.crm_create[b34ad226-f822-4b6c-a481-7c82b871b533] received
Nov 01 10:29:01 prospector python[1437238]: [2024-11-01 10:29:01,964: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7f31bcb8e5c0> (args:('prospector.apps.crm.tasks.crm_create', 'b34ad226-f822-4b6c-a481-7c82b871b533', {'lang': 'py', 'task': 'prospector.apps.crm.tasks.crm_create', 'id': 'b34ad226-f822-4b6c-a481-7c82b871b533', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'b34ad226-f822-4b6c-a481-7c82b871b533', 'parent_id': None, 'argsrepr': "('7d645577-e307-4413-ab16-750a9c7fd14b',)", 'kwargsrepr': '{}', 'origin': 'gen168843@prospector', 'ignore_result': False, 'properties': {'correlation_id': 'b34ad226-f822-4b6c-a481-7c82b871b533', 'reply_to': '93e0bf0a-321a-3d52-854e-ef28521abc7b', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'celery'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': 'f4b1f498-0f61-4ca5-b793-1269c06c87ef'}, 'reply_to': '93e0bf0a-321a-3d52-854e-ef28521abc7b', 'correlation_id': 'b34ad226-f822-4b6c-a481-7c82b871b533', 'hostname': 'celery@prospector', 'delivery_info': {'exchange': '', 'routing_key': 'celery',... kwargs:{})
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,419: DEBUG/ForkPoolWorker-1] Invoking 0 protected resource request hooks.
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,420: DEBUG/ForkPoolWorker-1] Adding token {'token_type': 'Bearer', 'expires_in': '3599', 'ext_expires_in': '3599', 'expires_on': '1730116496', 'not_before': '1730112596', 'resource': 'https://plymouthenergycommunity.crm4.dynamics.com/', 'access_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjNQYUs0RWZ5Qk5RdTNDdGpZc2EzWW1oUTVFMCIsImtpZCI6IjNQYUs0RWZ5Qk5RdTNDdGpZc2EzWW1oUTVFMCJ9.eyJhdWQiOiJodHRwczovL3BseW1vdXRoZW5lcmd5Y29tbXVuaXR5LmNybTQuZHluYW1pY3MuY29tLyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2JhNDdkNDIyLWRhZDAtNGVmYS1hZjkzLTFmNmQ1YzNkYmJlYy8iLCJpYXQiOjE3MzAxMTI1OTYsIm5iZiI6MTczMDExMjU5NiwiZXhwIjoxNzMwMTE2NDk2LCJhaW8iOiJrMkJnWU5BcDI3aHN5Zi9sOVN5cWgyMzliNjRLQlFBPSIsImFwcGlkIjoiOTgwZGI0YTgtYzZjYS00MjdhLTkzNGUtNDM2NzZjY2RmZGM4IiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvYmE0N2Q0MjItZGFkMC00ZWZhLWFmOTMtMWY2ZDVjM2RiYmVjLyIsImlkdHlwIjoiYXBwIiwib2lkIjoiMDQ4ODA5NGItMTZhMi00NzE3LTljYWYtZjJlYjI2NDYwODE5IiwicmgiOiIwLkFSRUFJdFJIdXREYS1rNnZreDl0WEQyNzdBY0FBQUFBQUFBQXdBQUFBQUFBQUFBWEFRQS4iLCJzdWIiOiIwNDg4MDk0Yi0xNmEyLTQ3MTctOWNhZi1mMmViMjY0NjA4MTkiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiRVUiLCJ0aWQiOiJiYTQ3ZDQyMi1kYWQwLTRlZmEtYWY5My0xZjZkNWMzZGJiZWMiLCJ1dGkiOiJMTnlxQ3dwdnMwR3pMdjJvNHhzZkFBIiwidmVyIjoiMS4wIiwieG1zX2lkcmVsIjoiNyAxMCJ9.H-WSuiOt9hvhDT8D7n9DLF63HTWBxlP10J_XaDyjNm8q7fqQJqU80dMZtihrDdct9eNIwWcRcll26IEz6onoV0VTt6ymM_OCBWDazebSxbXS5EBET6Akjpaw-UCCX3LjMPG1g0BaDb5ucoT0yV5yoBglkboLCQ8Z8sI2jI1IY88qL3DKUTQFDbZL_GD5uY5M_oogXIrud8P2XRRL6Yz8Qb5vrzWu1DYACK6T6uiF81CxeYcPCle6fsTMWePe4qROCp7ib6s4FXSJ3FCCu-Iz6A6FZ2mvPimfpeE9As61O_shQrUYU9Oa0jU2tXWjG1CV7N1qsl5QPQMylHN8gClaPw', 'expires_at': 1730116495.5122354} to request.
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,421: DEBUG/ForkPoolWorker-1] Requesting url https://login.microsoftonline.com/ba47d422-dad0-4efa-af93-1f6d5c3dbbec/oauth2/token using method POST.
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,421: DEBUG/ForkPoolWorker-1] Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'client_credentials', 'client_id': '980db4a8-c6ca-427a-934e-43676ccdfdc8', 'client_secret': 'isN8Q~cnpVfaQ1XUytpFJhbPJmlA8nV3ahxKFccw', 'resource': 'https://plymouthenergycommunity.crm4.dynamics.com/'}
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,421: DEBUG/ForkPoolWorker-1] Passing through key word arguments {'timeout': None, 'auth': None, 'verify': True, 'proxies': None, 'cert': None}.
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,423: DEBUG/ForkPoolWorker-1] Starting new HTTPS connection (1): login.microsoftonline.com:443
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,602: DEBUG/ForkPoolWorker-1] https://login.microsoftonline.com:443 "POST /ba47d422-dad0-4efa-af93-1f6d5c3dbbec/oauth2/token HTTP/1.1" 401 695
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,604: DEBUG/ForkPoolWorker-1] Request to fetch token completed with status 401.
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,604: DEBUG/ForkPoolWorker-1] Request url was https://login.microsoftonline.com/ba47d422-dad0-4efa-af93-1f6d5c3dbbec/oauth2/token
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,605: DEBUG/ForkPoolWorker-1] Request headers were {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Content-Length': '199'}
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,605: DEBUG/ForkPoolWorker-1] Request body was grant_type=client_credentials&client_id=980db4a8-c6ca-427a-934e-43676ccdfdc8&client_secret=isN8Q~cnpVfaQ1XUytpFJhbPJmlA8nV3ahxKFccw&resource=https%3A%2F%2Fplymouthenergycommunity.crm4.dynamics.com%2F
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,605: DEBUG/ForkPoolWorker-1] Response headers were {'Cache-Control': 'no-store, no-cache', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'P3P': 'CP="DSP CUR OTPi IND OTRi ONL FIN"', 'x-ms-request-id': 'ab4a6819-fd7e-4d82-9bf2-d4f42eeb0b00', 'x-ms-ests-server': '2.1.19267.5 - NEULR1 ProdSlices', 'x-ms-srs': '1.P', 'X-XSS-Protection': '0', 'Set-Cookie': 'fpc=Ahd1k4B4WMRHgodrmRQ4vkacs3lCAQAAAG6ktt4OAAAA; expires=Sun, 01-Dec-2024 10:29:02 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly', 'Date': 'Fri, 01 Nov 2024 10:29:01 GMT', 'Content-Length': '695'} and content {"error":"invalid_client","error_description":"AADSTS7000222: The provided client secret keys for app '980db4a8-c6ca-427a-934e-43676ccdfdc8' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: ab4a6819-fd7e-4d82-9bf2-d4f42eeb0b00 Correlation ID: a2619613-0930-4505-a04d-9d1c2b3ce871 Timestamp: 2024-11-01 10:29:02Z","error_codes":[7000222],"timestamp":"2024-11-01 10:29:02Z","trace_id":"ab4a6819-fd7e-4d82-9bf2-d4f42eeb0b00","correlation_id":"a2619613-0930-4505-a04d-9d1c2b3ce871","error_uri":"https://login.microsoftonline.com/error?code=7000222"}.
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,606: DEBUG/ForkPoolWorker-1] Invoking 0 token response hooks.
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,621: WARNING/ForkPoolWorker-1] --- Logging error ---
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,623: WARNING/ForkPoolWorker-1] Traceback (most recent call last):
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,624: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 40, in crm_create
Nov 01 10:29:02 prospector python[1437248]:     result = crm.create_pcc_record(crm_create.session, crm.map_crm(answers))
Nov 01 10:29:02 prospector python[1437248]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,624: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apis/crm/crm.py", line 674, in create_pcc_record
Nov 01 10:29:02 prospector python[1437248]:     return crm_request(client, query, json=crm_data, request_method="POST")
Nov 01 10:29:02 prospector python[1437248]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,625: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apis/crm/crm.py", line 73, in crm_request
Nov 01 10:29:02 prospector python[1437248]:     return session.request(
Nov 01 10:29:02 prospector python[1437248]:            ^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,625: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 483, in request
Nov 01 10:29:02 prospector python[1437248]:     url, headers, data = self._client.add_token(
Nov 01 10:29:02 prospector python[1437248]:                          ^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,625: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
Nov 01 10:29:02 prospector python[1437248]:     raise TokenExpiredError()
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,626: WARNING/ForkPoolWorker-1] oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,626: WARNING/ForkPoolWorker-1]
Nov 01 10:29:02 prospector python[1437248]: During handling of the above exception, another exception occurred:
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,626: WARNING/ForkPoolWorker-1] Traceback (most recent call last):
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,627: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
Nov 01 10:29:02 prospector python[1437248]:     R = retval = fun(*args, **kwargs)
Nov 01 10:29:02 prospector python[1437248]:                  ^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,627: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
Nov 01 10:29:02 prospector python[1437248]:     return self.run(*args, **kwargs)
Nov 01 10:29:02 prospector python[1437248]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,628: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 47, in crm_create
Nov 01 10:29:02 prospector python[1437248]:     raise e  # re-raise for celery
Nov 01 10:29:02 prospector python[1437248]:     ^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,628: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 44, in crm_create
Nov 01 10:29:02 prospector python[1437248]:     result = crm.create_pcc_record(crm_create.new_session, crm.map_crm(answers))
Nov 01 10:29:02 prospector python[1437248]:                                    ^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,628: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/local.py", line 143, in __getattr__
Nov 01 10:29:02 prospector python[1437248]:     return getattr(self._get_current_object(), name)
Nov 01 10:29:02 prospector python[1437248]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,629: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 26, in new_session
Nov 01 10:29:02 prospector python[1437248]:     self._session = crm.get_authorised_session(client)
Nov 01 10:29:02 prospector python[1437248]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,629: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apis/crm/crm.py", line 56, in get_authorised_session
Nov 01 10:29:02 prospector python[1437248]:     session.fetch_token(**settings)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,629: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 366, in fetch_token
Nov 01 10:29:02 prospector python[1437248]:     self._client.parse_request_body_response(r.text, scope=self.scope)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,629: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
Nov 01 10:29:02 prospector python[1437248]:     self.token = parse_token_response(body, scope=scope)
Nov 01 10:29:02 prospector python[1437248]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,629: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
Nov 01 10:29:02 prospector python[1437248]:     validate_token_parameters(params)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,630: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
Nov 01 10:29:02 prospector python[1437248]:     raise_from_error(params.get('error'), params)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,630: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
Nov 01 10:29:02 prospector python[1437248]:     raise cls(**kwargs)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,630: WARNING/ForkPoolWorker-1] oauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client) AADSTS7000222: The provided client secret keys for app '980db4a8-c6ca-427a-934e-43676ccdfdc8' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: ab4a6819-fd7e-4d82-9bf2-d4f42eeb0b00 Correlation ID: a2619613-0930-4505-a04d-9d1c2b3ce871 Timestamp: 2024-11-01 10:29:02Z
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,631: WARNING/ForkPoolWorker-1]
Nov 01 10:29:02 prospector python[1437248]: During handling of the above exception, another exception occurred:
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,631: WARNING/ForkPoolWorker-1] Traceback (most recent call last):
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,631: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
Nov 01 10:29:02 prospector python[1437248]:     msg = self.format(record)
Nov 01 10:29:02 prospector python[1437248]:           ^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,632: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
Nov 01 10:29:02 prospector python[1437248]:     return fmt.format(record)
Nov 01 10:29:02 prospector python[1437248]:            ^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,632: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/utils/log.py", line 146, in format
Nov 01 10:29:02 prospector python[1437248]:     msg = super().format(record)
Nov 01 10:29:02 prospector python[1437248]:           ^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,632: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/logging/__init__.py", line 695, in format
Nov 01 10:29:02 prospector python[1437248]:     record.exc_text = self.formatException(record.exc_info)
Nov 01 10:29:02 prospector python[1437248]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,633: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/utils/log.py", line 142, in formatException
Nov 01 10:29:02 prospector python[1437248]:     r = super().formatException(ei)
Nov 01 10:29:02 prospector python[1437248]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,633: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/logging/__init__.py", line 645, in formatException
Nov 01 10:29:02 prospector python[1437248]:     traceback.print_exception(ei[0], ei[1], tb, None, sio)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,633: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/traceback.py", line 124, in print_exception
Nov 01 10:29:02 prospector python[1437248]:     te = TracebackException(type(value), value, tb, limit=limit, compact=True)
Nov 01 10:29:02 prospector python[1437248]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,633: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/traceback.py", line 692, in __init__
Nov 01 10:29:02 prospector python[1437248]:     self.stack = StackSummary._extract_from_extended_frame_gen(
Nov 01 10:29:02 prospector python[1437248]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,634: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/traceback.py", line 416, in _extract_from_extended_frame_gen
Nov 01 10:29:02 prospector python[1437248]:     for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,634: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/traceback.py", line 353, in _walk_tb_with_full_positions
Nov 01 10:29:02 prospector python[1437248]:     positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
Nov 01 10:29:02 prospector python[1437248]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,634: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/traceback.py", line 366, in _get_code_position
Nov 01 10:29:02 prospector python[1437248]:     positions_gen = code.co_positions()
Nov 01 10:29:02 prospector python[1437248]:                     ^^^^^^^^^^^^^^^^^
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,634: WARNING/ForkPoolWorker-1] AttributeError: '_Code' object has no attribute 'co_positions'
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,634: WARNING/ForkPoolWorker-1] Call stack:
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,635: WARNING/ForkPoolWorker-1]   File "<frozen runpy>", line 198, in _run_module_as_main
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,635: WARNING/ForkPoolWorker-1]   File "<frozen runpy>", line 88, in _run_code
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,636: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/__main__.py", line 19, in <module>
Nov 01 10:29:02 prospector python[1437248]:     main()
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,636: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
Nov 01 10:29:02 prospector python[1437248]:     sys.exit(_main())
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,636: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/bin/celery.py", line 217, in main
Nov 01 10:29:02 prospector python[1437248]:     return celery(auto_envvar_prefix="CELERY")
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,636: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
Nov 01 10:29:02 prospector python[1437248]:     return self.main(*args, **kwargs)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,637: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
Nov 01 10:29:02 prospector python[1437248]:     rv = self.invoke(ctx)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,637: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
Nov 01 10:29:02 prospector python[1437248]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,637: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
Nov 01 10:29:02 prospector python[1437248]:     return ctx.invoke(self.callback, **ctx.params)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,637: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
Nov 01 10:29:02 prospector python[1437248]:     return __callback(*args, **kwargs)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,637: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
Nov 01 10:29:02 prospector python[1437248]:     return f(get_current_context(), *args, **kwargs)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,638: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
Nov 01 10:29:02 prospector python[1437248]:     return f(ctx, *args, **kwargs)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,638: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/bin/worker.py", line 351, in worker
Nov 01 10:29:02 prospector python[1437248]:     worker.start()
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,638: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/worker/worker.py", line 203, in start
Nov 01 10:29:02 prospector python[1437248]:     self.blueprint.start(self)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,638: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
Nov 01 10:29:02 prospector python[1437248]:     step.start(parent)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,639: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
Nov 01 10:29:02 prospector python[1437248]:     return self.obj.start()
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,639: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/concurrency/base.py", line 129, in start
Nov 01 10:29:02 prospector python[1437248]:     self.on_start()
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,639: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/concurrency/prefork.py", line 109, in on_start
Nov 01 10:29:02 prospector python[1437248]:     P = self._pool = Pool(processes=self.limit,
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,639: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 463, in __init__
Nov 01 10:29:02 prospector python[1437248]:     super().__init__(processes, *args, **kwargs)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,639: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/pool.py", line 1046, in __init__
Nov 01 10:29:02 prospector python[1437248]:     self._create_worker_process(i)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,640: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 480, in _create_worker_process
Nov 01 10:29:02 prospector python[1437248]:     return super()._create_worker_process(i)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,640: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/pool.py", line 1158, in _create_worker_process
Nov 01 10:29:02 prospector python[1437248]:     w.start()
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,640: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/process.py", line 124, in start
Nov 01 10:29:02 prospector python[1437248]:     self._popen = self._Popen(self)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,641: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/context.py", line 333, in _Popen
Nov 01 10:29:02 prospector python[1437248]:     return Popen(process_obj)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,641: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/popen_fork.py", line 24, in __init__
Nov 01 10:29:02 prospector python[1437248]:     self._launch(process_obj)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,641: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/popen_fork.py", line 79, in _launch
Nov 01 10:29:02 prospector python[1437248]:     code = process_obj._bootstrap()
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,641: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/process.py", line 327, in _bootstrap
Nov 01 10:29:02 prospector python[1437248]:     self.run()
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,642: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/process.py", line 114, in run
Nov 01 10:29:02 prospector python[1437248]:     self._target(*self._args, **self._kwargs)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,642: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/pool.py", line 292, in __call__
Nov 01 10:29:02 prospector python[1437248]:     sys.exit(self.workloop(pid=pid))
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,642: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/pool.py", line 362, in workloop
Nov 01 10:29:02 prospector python[1437248]:     result = (True, prepare_result(fun(*args, **kwargs)))
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,642: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 649, in fast_trace_task
Nov 01 10:29:02 prospector python[1437248]:     R, I, T, Rstr = tasks[task].__trace__(
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,642: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 468, in trace_task
Nov 01 10:29:02 prospector python[1437248]:     I, R, state, retval = on_error(task_request, exc, uuid)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,643: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 379, in on_error
Nov 01 10:29:02 prospector python[1437248]:     R = I.handle_error_state(
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,643: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 178, in handle_error_state
Nov 01 10:29:02 prospector python[1437248]:     return {
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,643: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 237, in handle_failure
Nov 01 10:29:02 prospector python[1437248]:     self._log_error(task, req, einfo)
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,643: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 265, in _log_error
Nov 01 10:29:02 prospector python[1437248]:     logger.log(policy.severity, policy.format.strip(), context,
Nov 01 10:29:02 prospector python[1437248]: [2024-11-01 10:29:02,644: WARNING/ForkPoolWorker-1] Message: 'Task %(name)s[%(id)s] %(description)s: %(exc)s'
Nov 01 10:29:02 prospector python[1437248]: Arguments: {'hostname': 'celery@prospector', 'id': 'b34ad226-f822-4b6c-a481-7c82b871b533', 'name': 'prospector.apps.crm.tasks.crm_create', 'exc': 'InvalidClientError("(invalid_client) AADSTS7000222: The provided client secret keys for app \'980db4a8-c6ca-427a-934e-43676ccdfdc8\' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: ab4a6819-fd7e-4d82-9bf2-d4f42eeb0b00 Correlation ID: a2619613-0930-4505-a04d-9d1c2b3ce871 Timestamp: 2024-11-01 10:29:02Z")', 'traceback': 'Traceback (most recent call last):\n  File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 40, in crm_create\n    result = crm.create_pcc_record(crm_create.session, crm.map_crm(answers))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/prospector/prospector/apis/crm/crm.py", line 674, in create_pcc_record\n    return crm_request(client, query, json=crm_data, request_method="POST")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/prospector/prospector/apis/crm/crm.py", line 73, in crm_request\n    return session.request(\n           ^^^^^^^^^^^^^^^^\n  File "/home/plymouth/venv/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 483, in request\n    url, headers, data = self._client.add_token(\n                         ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token\n    raise TokenExpiredError()\noauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) \n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 47, in crm_create\n    raise e  # re-raise for celery\n    ^^^^^^^\n  File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 44, in crm_create\n    result = crm.create_pcc_record(crm_create.new_session, crm.map_crm(answers))\n                                   ^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/venv/lib/python3.11/site-packages/celery/local.py", line 143, in __getattr__\n    return getattr(self._get_current_object(), name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 26, in new_session\n    self._session = crm.get_authorised_session(client)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/prospector/prospector/apis/crm/crm.py", line 56, in get_authorised_session\n    session.fetch_token(**settings)\n  File "/home/plymouth/venv/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 366, in fetch_token\n    self._client.parse_request_body_response(r.text, scope=self.scope)\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response\n    self.token = parse_token_response(body, scope=scope)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response\n    validate_token_parameters(params)\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters\n    raise_from_error(params.get(\'error\'), params)\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error\n    raise cls(**kwargs)\noauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client) AADSTS7000222: The provided client secret keys for app \'980db4a8-c6ca-427a-934e-43676ccdfdc8\' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: ab4a6819-fd7e-4d82-9bf2-d4f42eeb0b00 Correlation ID: a2619613-0930-4505-a04d-9d1c2b3ce871 Timestamp: 2024-11-01 10:29:02Z\n', 'args': "['7d645577-e307-4413-ab16-750a9c7fd14b']", 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}
Nov 01 10:32:20 prospector python[1437238]: worker: Warm shutdown (MainProcess)
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,266: DEBUG/MainProcess] | Worker: Closing Hub...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,266: DEBUG/MainProcess] | Worker: Closing Pool...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,266: DEBUG/MainProcess] | Worker: Closing Consumer...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,266: DEBUG/MainProcess] | Worker: Stopping Consumer...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,266: DEBUG/MainProcess] | Consumer: Closing Connection...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,266: DEBUG/MainProcess] | Consumer: Closing Events...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,266: DEBUG/MainProcess] | Consumer: Closing Mingle...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,266: DEBUG/MainProcess] | Consumer: Closing Tasks...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,266: DEBUG/MainProcess] | Consumer: Closing Control...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,266: DEBUG/MainProcess] | Consumer: Closing Heart...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,267: DEBUG/MainProcess] | Consumer: Closing Gossip...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,267: DEBUG/MainProcess] | Consumer: Closing event loop...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,267: DEBUG/MainProcess] | Consumer: Stopping event loop...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,267: DEBUG/MainProcess] | Consumer: Stopping Gossip...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,274: DEBUG/MainProcess] | Consumer: Stopping Heart...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,277: DEBUG/MainProcess] | Consumer: Stopping Control...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,279: DEBUG/MainProcess] | Consumer: Stopping Tasks...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,279: DEBUG/MainProcess] Canceling task consumer...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,280: DEBUG/MainProcess] | Consumer: Stopping Mingle...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,281: DEBUG/MainProcess] | Consumer: Stopping Events...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,281: DEBUG/MainProcess] | Consumer: Stopping Connection...
Nov 01 10:32:20 prospector python[1437238]: [2024-11-01 10:32:20,281: DEBUG/MainProcess] | Worker: Stopping Pool...
Nov 01 10:32:21 prospector python[1437238]: [2024-11-01 10:32:21,293: DEBUG/MainProcess] | Worker: Stopping Hub...
Nov 01 10:32:21 prospector python[1437238]: [2024-11-01 10:32:21,294: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
Nov 01 10:32:21 prospector python[1437238]: [2024-11-01 10:32:21,294: DEBUG/MainProcess] | Consumer: Shutdown Heart...
Nov 01 10:32:21 prospector python[1437238]: [2024-11-01 10:32:21,297: DEBUG/MainProcess] | Consumer: Shutdown Control...
Nov 01 10:32:21 prospector python[1437238]: [2024-11-01 10:32:21,297: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
Nov 01 10:32:21 prospector python[1437238]: [2024-11-01 10:32:21,297: DEBUG/MainProcess] Canceling task consumer...
Nov 01 10:32:21 prospector python[1437238]: [2024-11-01 10:32:21,297: DEBUG/MainProcess] Closing consumer channel...
Nov 01 10:32:21 prospector python[1437238]: [2024-11-01 10:32:21,297: DEBUG/MainProcess] | Consumer: Shutdown Events...
Nov 01 10:32:21 prospector python[1437238]: [2024-11-01 10:32:21,298: DEBUG/MainProcess] | Consumer: Shutdown Connection...
Nov 01 10:32:21 prospector python[1437238]: [2024-11-01 10:32:21,300: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,675: DEBUG/MainProcess] | Worker: Preparing bootsteps.
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,678: DEBUG/MainProcess] | Worker: Building graph...
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,679: DEBUG/MainProcess] | Worker: New boot order: {Beat, Timer, Hub, Pool, Autoscaler, StateDB, Consumer}
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,689: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,689: DEBUG/MainProcess] | Consumer: Building graph...
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,700: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Tasks, Control, Gossip, Agent, Heart, event loop}
Nov 01 10:32:25 prospector python[218853]:  
Nov 01 10:32:25 prospector python[218853]:  -------------- celery@prospector v5.2.7 (dawn-chorus)
Nov 01 10:32:25 prospector python[218853]: --- ***** -----
Nov 01 10:32:25 prospector python[218853]: -- ******* ---- Linux-6.2.0-20-generic-x86_64-with-glibc2.37 2024-11-01 10:32:25
Nov 01 10:32:25 prospector python[218853]: - *** --- * ---
Nov 01 10:32:25 prospector python[218853]: - ** ---------- [config]
Nov 01 10:32:25 prospector python[218853]: - ** ---------- .> app:         proj:0x7f56765447d0
Nov 01 10:32:25 prospector python[218853]: - ** ---------- .> transport:   redis://localhost:6379/0
Nov 01 10:32:25 prospector python[218853]: - ** ---------- .> results:
Nov 01 10:32:25 prospector python[218853]: - *** --- * --- .> concurrency: 1 (prefork)
Nov 01 10:32:25 prospector python[218853]: -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
Nov 01 10:32:25 prospector python[218853]: --- ***** -----
Nov 01 10:32:25 prospector python[218853]:  -------------- [queues]
Nov 01 10:32:25 prospector python[218853]:                 .> celery           exchange=celery(direct) key=celery
Nov 01 10:32:25 prospector python[218853]:                 
Nov 01 10:32:25 prospector python[218853]: [tasks]
Nov 01 10:32:25 prospector python[218853]:   . celery.accumulate
Nov 01 10:32:25 prospector python[218853]:   . celery.backend_cleanup
Nov 01 10:32:25 prospector python[218853]:   . celery.chain
Nov 01 10:32:25 prospector python[218853]:   . celery.chord
Nov 01 10:32:25 prospector python[218853]:   . celery.chord_unlock
Nov 01 10:32:25 prospector python[218853]:   . celery.chunks
Nov 01 10:32:25 prospector python[218853]:   . celery.group
Nov 01 10:32:25 prospector python[218853]:   . celery.map
Nov 01 10:32:25 prospector python[218853]:   . celery.starmap
Nov 01 10:32:25 prospector python[218853]:   . prospector.apps.crm.celery.debug_task
Nov 01 10:32:25 prospector python[218853]:   . prospector.apps.crm.tasks.crm_create
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,710: DEBUG/MainProcess] | Worker: Starting Hub
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,710: DEBUG/MainProcess] ^-- substep ok
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,711: DEBUG/MainProcess] | Worker: Starting Pool
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,796: DEBUG/MainProcess] ^-- substep ok
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,801: DEBUG/MainProcess] | Worker: Starting Consumer
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,802: DEBUG/MainProcess] | Consumer: Starting Connection
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,821: INFO/MainProcess] Connected to redis://localhost:6379/0
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,822: DEBUG/MainProcess] ^-- substep ok
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,822: DEBUG/MainProcess] | Consumer: Starting Events
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,828: DEBUG/MainProcess] ^-- substep ok
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,830: DEBUG/MainProcess] | Consumer: Starting Mingle
Nov 01 10:32:25 prospector python[218853]: [2024-11-01 10:32:25,830: INFO/MainProcess] mingle: searching for neighbors
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,852: INFO/MainProcess] mingle: all alone
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,853: DEBUG/MainProcess] ^-- substep ok
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,853: DEBUG/MainProcess] | Consumer: Starting Tasks
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,857: DEBUG/MainProcess] ^-- substep ok
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,857: DEBUG/MainProcess] | Consumer: Starting Control
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,860: DEBUG/MainProcess] ^-- substep ok
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,861: DEBUG/MainProcess] | Consumer: Starting Gossip
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,864: DEBUG/MainProcess] ^-- substep ok
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,864: DEBUG/MainProcess] | Consumer: Starting Heart
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,865: DEBUG/MainProcess] ^-- substep ok
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,866: DEBUG/MainProcess] | Consumer: Starting event loop
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,866: DEBUG/MainProcess] | Worker: Hub.register Pool...
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,869: WARNING/MainProcess] /home/plymouth/venv/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
Nov 01 10:32:26 prospector python[218853]:             leak, never use this setting in production environments!
Nov 01 10:32:26 prospector python[218853]:   warnings.warn('''Using settings.DEBUG leads to a memory
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,869: INFO/MainProcess] celery@prospector ready.
Nov 01 10:32:26 prospector python[218853]: [2024-11-01 10:32:26,870: DEBUG/MainProcess] basic.qos: prefetch_count->4
Nov 01 10:32:28 prospector python[218853]: [2024-11-01 10:32:28,747: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '5dca85eb-1faa-3995-b36a-2ca0d43867c1'} ticket:3d62946e-6c95-4916-9b60-8039beb50f5f]
Nov 01 10:32:30 prospector python[218853]: [2024-11-01 10:32:30,863: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'b4e77e49-5c65-38e0-99d9-c570ebf9c3e6'} ticket:265c3524-66ca-44b3-9619-059b4840dd85]
Nov 01 10:32:32 prospector python[218853]: [2024-11-01 10:32:32,814: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '2a3db0a0-291c-3423-8af3-304d9ecda4e6'} ticket:2c72b554-f6c4-4a80-bd81-9bca5e2ec41e]
Nov 01 10:32:34 prospector python[218853]: [2024-11-01 10:32:34,895: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '109ca444-4b50-385b-8bf3-21a13fbccb4a'} ticket:75bf0e8a-ed08-408e-9225-736eae29ab50]
Nov 01 10:32:37 prospector python[218853]: [2024-11-01 10:32:37,250: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '1c8fcf9b-8abe-3c8c-aa3e-e6e75c50a1f5'} ticket:d23e1c01-9f91-46be-8d84-72a16b00ca44]
Nov 01 10:32:39 prospector python[218853]: [2024-11-01 10:32:39,298: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'bad262ac-7195-3bd9-8d8a-8339e5f46da2'} ticket:e9a52b40-00a8-43d5-a798-dfaeb9d3b83e]
Nov 01 10:32:41 prospector python[218853]: [2024-11-01 10:32:41,352: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '7df1c9cd-f7cc-31a3-8320-311cb9749f77'} ticket:6a4dfb4d-fd56-4039-8673-fc49e93f01a0]
Nov 01 10:32:43 prospector python[218853]: [2024-11-01 10:32:43,475: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'abab6851-3713-307a-8225-2b381caf1972'} ticket:53249fc8-d50a-4e44-b1c3-77ef9d06ad50]
Nov 01 10:32:45 prospector python[218853]: [2024-11-01 10:32:45,700: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '0891ef92-eed7-30e2-86e0-6d9e30493007'} ticket:d02f358e-eeb1-4239-b559-b47fb5b3dffa]
Nov 01 10:32:47 prospector python[218853]: [2024-11-01 10:32:47,852: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '777216db-c223-3037-81e7-b2caa3e98e8b'} ticket:6bfdbece-7d27-42b9-9e34-4c6e327879d0]
Nov 01 10:32:49 prospector python[218853]: [2024-11-01 10:32:49,835: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'ce1010c6-bfe7-3db2-87af-cb54edf964e8'} ticket:907796c4-310f-48e9-b0db-d3632c54b74f]
Nov 01 10:32:51 prospector python[218853]: [2024-11-01 10:32:51,805: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '935dd4d7-8094-38b4-9e2d-6b9ae24f9164'} ticket:5448daa7-6408-40c2-a4d0-10fd086e028e]
Nov 01 10:32:53 prospector python[218853]: [2024-11-01 10:32:53,845: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '1aba7223-e157-3a82-9d58-4a42243cda5e'} ticket:8c1df538-b02e-4425-aac8-370e55809051]
Nov 01 10:32:56 prospector python[218853]: [2024-11-01 10:32:56,011: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'f5cc915f-cdcf-3690-9b32-531dc550c02f'} ticket:a18065d3-e9cb-4c88-a198-3b7fde0a4325]
Nov 01 10:32:58 prospector python[218853]: [2024-11-01 10:32:58,243: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '0f680202-47d6-311e-9f90-97c86826a2ea'} ticket:62c8b1e8-2d96-4577-9c5a-c709fd74b6ef]
Nov 01 10:33:00 prospector python[218853]: [2024-11-01 10:33:00,546: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '94326507-bea8-35c6-aea3-ee2564fc6df5'} ticket:20ca6203-166c-41e9-ba0a-6125e5e8e34e]
Nov 01 10:33:02 prospector python[218853]: [2024-11-01 10:33:02,748: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '7d0c4617-588e-3090-baa7-56dea506276c'} ticket:36effd26-53b8-4fcf-b099-f3f62db175cc]
Nov 01 10:33:05 prospector python[218853]: [2024-11-01 10:33:05,032: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'd83f6bec-9ca2-3f48-97d0-8c388dda78d3'} ticket:a8e322e1-c142-4a6f-9c5c-6f6e35ed6ea7]
Nov 01 10:33:07 prospector python[218853]: [2024-11-01 10:33:07,136: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '2c27741a-2ae3-3500-ac71-9bfd15297dcd'} ticket:38860000-8c2c-4a8c-b56a-f8da1e243798]
Nov 01 10:33:09 prospector python[218853]: [2024-11-01 10:33:09,510: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'd7c4fcc0-0f57-380e-9125-d35f65ecd2e4'} ticket:ad9bedd6-e0da-4aa5-b63e-82103a150c94]
Nov 01 10:33:11 prospector python[218853]: [2024-11-01 10:33:11,760: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'ffcf9816-6531-3ce4-9208-d952d1770725'} ticket:aad3723b-8a35-4ebd-b110-b78817871f68]
Nov 01 10:33:13 prospector python[218853]: [2024-11-01 10:33:13,873: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'fbb7cb8b-b9a8-3054-a993-61cbe9b5f35d'} ticket:affb918d-bf92-42fa-9daa-7e510b34e31c]
Nov 01 10:33:16 prospector python[218853]: [2024-11-01 10:33:16,126: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '2570d70f-835d-3e30-a220-9db768e72a97'} ticket:093b021c-d408-43fe-a096-f8eab48af2fd]
Nov 01 10:33:18 prospector python[218853]: [2024-11-01 10:33:18,352: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '3928c69d-eee6-3440-acab-4d241e929a5b'} ticket:2af1ace2-3287-447c-b016-be3159e78365]
Nov 01 10:33:20 prospector python[218853]: [2024-11-01 10:33:20,602: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'b657d503-ae78-324a-973e-41920575ca06'} ticket:c737bc3d-4447-4f05-8bc4-2c724e3335df]
Nov 01 10:33:22 prospector python[218853]: [2024-11-01 10:33:22,652: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'ffa6e7ee-97a9-30f0-aaa5-cb8b84f656cd'} ticket:8511fc2b-682f-4028-affa-070ac5345b99]
Nov 01 10:33:24 prospector python[218853]: [2024-11-01 10:33:24,997: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '1d702e01-b27a-3a67-938d-9d6ad69a54f0'} ticket:5e5ff8cc-9b1a-403f-83a7-b060716f5509]
Nov 01 10:33:27 prospector python[218853]: [2024-11-01 10:33:27,287: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '3137dc69-1701-3860-9ea2-bd79c127af48'} ticket:3e2115cb-7780-46ca-b3e7-311c5e7f506e]
Nov 01 10:33:29 prospector python[218853]: [2024-11-01 10:33:29,394: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '3d490257-a338-37b1-b4e7-c94356ab1c7b'} ticket:098b1e8f-1ad9-4148-8365-3e8f711bf38b]
Nov 01 10:33:31 prospector python[218853]: [2024-11-01 10:33:31,686: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'a964f4c1-d9c7-3b0e-8776-56356f9b1a62'} ticket:8c21f7fa-8c86-425b-aa72-961741873ea4]
Nov 01 10:33:33 prospector python[218853]: [2024-11-01 10:33:33,876: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '03e977d0-982c-3e15-88c7-8705c079ba09'} ticket:7468902e-5431-4d33-923f-5ee151db2c60]
Nov 01 10:33:36 prospector python[218853]: [2024-11-01 10:33:36,253: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '05393eee-a3b6-3a6b-931a-e77917d7402c'} ticket:145405a1-e433-433b-b1ac-7867d3435e28]
Nov 01 10:33:38 prospector python[218853]: [2024-11-01 10:33:38,397: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'b3783505-7111-30bd-a233-6b3d2819389d'} ticket:53f537f9-742c-494f-ac86-5874ba3d0968]
Nov 01 10:33:40 prospector python[218853]: [2024-11-01 10:33:40,664: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '8fc34377-7af0-3411-afd5-77760bec1c25'} ticket:7504dd91-a1e8-4224-9e6d-67c3a514dc36]
Nov 01 10:33:42 prospector python[218853]: [2024-11-01 10:33:42,871: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '13a9df15-ec9d-30c0-ac12-2fedb710eaea'} ticket:b68eead1-73e8-4d65-b14d-5e6d2477178c]
Nov 01 10:33:45 prospector python[218853]: [2024-11-01 10:33:45,193: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '691db3be-5762-3cbe-a5d5-9f6487d95562'} ticket:0ec5fa38-7af9-42ce-9519-f0860c4b3aaa]
Nov 01 10:33:47 prospector python[218853]: [2024-11-01 10:33:47,569: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '7546191d-301c-3915-a559-dfb04e352678'} ticket:af8289db-e609-45c1-b5a4-8c956f7b6ec0]
Nov 01 10:33:49 prospector python[218853]: [2024-11-01 10:33:49,663: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '032d7cfc-843b-36eb-a5a4-b48fffc04a30'} ticket:cceedd80-3256-442b-86df-cef57c4fd581]
Nov 01 10:33:52 prospector python[218853]: [2024-11-01 10:33:52,000: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '9785dbfc-ec7a-3448-8ca5-effb39b2eecf'} ticket:c480a89d-f9d1-46d1-9af2-a1b478b66692]
Nov 01 10:33:54 prospector python[218853]: [2024-11-01 10:33:54,134: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '587edf17-776d-3ea9-a70e-b759eb5fff13'} ticket:071276ed-0036-4fb5-af72-8813c5160890]
Nov 01 10:33:56 prospector python[218853]: [2024-11-01 10:33:56,519: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'f1ff8cc4-b497-3373-967a-681462c3d78c'} ticket:1ea9590e-0f73-49cf-ad38-d00cd0fccac1]
Nov 01 10:33:58 prospector python[218853]: [2024-11-01 10:33:58,652: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'b9b1e34a-93cc-3548-a1c7-46fe1d837666'} ticket:78db8883-2730-4fba-8d87-1f4b5b371730]
Nov 01 10:34:00 prospector python[218853]: [2024-11-01 10:34:00,932: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '129034d4-70a4-38ac-bc43-68a61ef2311d'} ticket:c73dbbce-9f08-466c-903a-7f5b7f3b07c5]
Nov 01 10:34:03 prospector python[218853]: [2024-11-01 10:34:03,176: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'c83c6ddb-285e-3496-aca4-208e311ddb7b'} ticket:b087b700-5859-4012-a7a9-003f80bbdf0e]
Nov 01 10:34:05 prospector python[218853]: [2024-11-01 10:34:05,446: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '96ed7063-f860-3acc-b956-722c52c3f7ef'} ticket:cb3c597a-bcd6-4846-8108-bb3071840e36]
Nov 01 10:34:07 prospector python[218853]: [2024-11-01 10:34:07,673: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '01dc88a8-c128-3355-9107-ad625b491977'} ticket:28ddf122-25cf-4d5c-89f6-f1b060e67f8b]
Nov 01 10:34:07 prospector python[218853]: [2024-11-01 10:34:07,964: INFO/MainProcess] Task prospector.apps.crm.tasks.crm_create[f5f2b406-77eb-4eb3-97e2-4ee1628b9e42] received
Nov 01 10:34:07 prospector python[218853]: [2024-11-01 10:34:07,965: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7f567678e5c0> (args:('prospector.apps.crm.tasks.crm_create', 'f5f2b406-77eb-4eb3-97e2-4ee1628b9e42', {'lang': 'py', 'task': 'prospector.apps.crm.tasks.crm_create', 'id': 'f5f2b406-77eb-4eb3-97e2-4ee1628b9e42', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'f5f2b406-77eb-4eb3-97e2-4ee1628b9e42', 'parent_id': None, 'argsrepr': "('a718a9de-895f-41a2-86ea-1212eac24da7',)", 'kwargsrepr': '{}', 'origin': 'gen218852@prospector', 'ignore_result': False, 'properties': {'correlation_id': 'f5f2b406-77eb-4eb3-97e2-4ee1628b9e42', 'reply_to': '42f87373-5b99-394a-afc5-4dc318b94f78', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'celery'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': '33f1e74c-8f4e-4b7e-9796-a8dea9646106'}, 'reply_to': '42f87373-5b99-394a-afc5-4dc318b94f78', 'correlation_id': 'f5f2b406-77eb-4eb3-97e2-4ee1628b9e42', 'hostname': 'celery@prospector', 'delivery_info': {'exchange': '', 'routing_key': 'celery',... kwargs:{})
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,018: DEBUG/ForkPoolWorker-1] Requesting url https://login.microsoftonline.com/ba47d422-dad0-4efa-af93-1f6d5c3dbbec/oauth2/token using method POST.
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,019: DEBUG/ForkPoolWorker-1] Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'client_credentials', 'client_id': '980db4a8-c6ca-427a-934e-43676ccdfdc8', 'client_secret': 'isN8Q~cnpVfaQ1XUytpFJhbPJmlA8nV3ahxKFccw', 'resource': 'https://plymouthenergycommunity.crm4.dynamics.com/'}
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,019: DEBUG/ForkPoolWorker-1] Passing through key word arguments {'timeout': None, 'auth': None, 'verify': True, 'proxies': None, 'cert': None}.
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,024: DEBUG/ForkPoolWorker-1] Starting new HTTPS connection (1): login.microsoftonline.com:443
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,226: DEBUG/ForkPoolWorker-1] https://login.microsoftonline.com:443 "POST /ba47d422-dad0-4efa-af93-1f6d5c3dbbec/oauth2/token HTTP/1.1" 401 695
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,229: DEBUG/ForkPoolWorker-1] Request to fetch token completed with status 401.
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,230: DEBUG/ForkPoolWorker-1] Request url was https://login.microsoftonline.com/ba47d422-dad0-4efa-af93-1f6d5c3dbbec/oauth2/token
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,230: DEBUG/ForkPoolWorker-1] Request headers were {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Content-Length': '199'}
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,231: DEBUG/ForkPoolWorker-1] Request body was grant_type=client_credentials&client_id=980db4a8-c6ca-427a-934e-43676ccdfdc8&client_secret=isN8Q~cnpVfaQ1XUytpFJhbPJmlA8nV3ahxKFccw&resource=https%3A%2F%2Fplymouthenergycommunity.crm4.dynamics.com%2F
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,231: DEBUG/ForkPoolWorker-1] Response headers were {'Cache-Control': 'no-store, no-cache', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'P3P': 'CP="DSP CUR OTPi IND OTRi ONL FIN"', 'x-ms-request-id': '516aae45-49fb-4756-ba97-5dd6bd380b00', 'x-ms-ests-server': '2.1.19343.4 - WEULR1 ProdSlices', 'x-ms-srs': '1.P', 'X-XSS-Protection': '0', 'Set-Cookie': 'fpc=AoVqVCOvHVZCodI7Rp9dn6qcs3lCAQAAAKCltt4OAAAA; expires=Sun, 01-Dec-2024 10:34:08 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly', 'Date': 'Fri, 01 Nov 2024 10:34:07 GMT', 'Content-Length': '695'} and content {"error":"invalid_client","error_description":"AADSTS7000222: The provided client secret keys for app '980db4a8-c6ca-427a-934e-43676ccdfdc8' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: 516aae45-49fb-4756-ba97-5dd6bd380b00 Correlation ID: aeec71bf-8d9c-46cc-9e6f-469df2d4d7aa Timestamp: 2024-11-01 10:34:08Z","error_codes":[7000222],"timestamp":"2024-11-01 10:34:08Z","trace_id":"516aae45-49fb-4756-ba97-5dd6bd380b00","correlation_id":"aeec71bf-8d9c-46cc-9e6f-469df2d4d7aa","error_uri":"https://login.microsoftonline.com/error?code=7000222"}.
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,231: DEBUG/ForkPoolWorker-1] Invoking 0 token response hooks.
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,232: DEBUG/ForkPoolWorker-1] Requesting url https://login.microsoftonline.com/ba47d422-dad0-4efa-af93-1f6d5c3dbbec/oauth2/token using method POST.
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,233: DEBUG/ForkPoolWorker-1] Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'client_credentials', 'client_id': '980db4a8-c6ca-427a-934e-43676ccdfdc8', 'client_secret': 'isN8Q~cnpVfaQ1XUytpFJhbPJmlA8nV3ahxKFccw', 'resource': 'https://plymouthenergycommunity.crm4.dynamics.com/'}
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,233: DEBUG/ForkPoolWorker-1] Passing through key word arguments {'timeout': None, 'auth': None, 'verify': True, 'proxies': None, 'cert': None}.
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,234: DEBUG/ForkPoolWorker-1] Starting new HTTPS connection (1): login.microsoftonline.com:443
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,436: DEBUG/ForkPoolWorker-1] https://login.microsoftonline.com:443 "POST /ba47d422-dad0-4efa-af93-1f6d5c3dbbec/oauth2/token HTTP/1.1" 401 695
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,437: DEBUG/ForkPoolWorker-1] Request to fetch token completed with status 401.
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,438: DEBUG/ForkPoolWorker-1] Request url was https://login.microsoftonline.com/ba47d422-dad0-4efa-af93-1f6d5c3dbbec/oauth2/token
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,438: DEBUG/ForkPoolWorker-1] Request headers were {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Content-Length': '199'}
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,438: DEBUG/ForkPoolWorker-1] Request body was grant_type=client_credentials&client_id=980db4a8-c6ca-427a-934e-43676ccdfdc8&client_secret=isN8Q~cnpVfaQ1XUytpFJhbPJmlA8nV3ahxKFccw&resource=https%3A%2F%2Fplymouthenergycommunity.crm4.dynamics.com%2F
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,438: DEBUG/ForkPoolWorker-1] Response headers were {'Cache-Control': 'no-store, no-cache', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'P3P': 'CP="DSP CUR OTPi IND OTRi ONL FIN"', 'x-ms-request-id': 'c942564b-64c2-4427-b25a-2cc466956f00', 'x-ms-ests-server': '2.1.19267.5 - SEC ProdSlices', 'x-ms-srs': '1.P', 'X-XSS-Protection': '0', 'Set-Cookie': 'fpc=AiHiq_lS8SxGrIQro6VutYqcs3lCAQAAAJ-ltt4OAAAA; expires=Sun, 01-Dec-2024 10:34:08 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly', 'Date': 'Fri, 01 Nov 2024 10:34:07 GMT', 'Content-Length': '695'} and content {"error":"invalid_client","error_description":"AADSTS7000222: The provided client secret keys for app '980db4a8-c6ca-427a-934e-43676ccdfdc8' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: c942564b-64c2-4427-b25a-2cc466956f00 Correlation ID: 940300de-6c27-4c67-ac8d-23a69b906a3b Timestamp: 2024-11-01 10:34:08Z","error_codes":[7000222],"timestamp":"2024-11-01 10:34:08Z","trace_id":"c942564b-64c2-4427-b25a-2cc466956f00","correlation_id":"940300de-6c27-4c67-ac8d-23a69b906a3b","error_uri":"https://login.microsoftonline.com/error?code=7000222"}.
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,439: DEBUG/ForkPoolWorker-1] Invoking 0 token response hooks.
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,458: WARNING/ForkPoolWorker-1] --- Logging error ---
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,461: WARNING/ForkPoolWorker-1] Traceback (most recent call last):
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,462: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 40, in crm_create
Nov 01 10:34:08 prospector python[218861]:     result = crm.create_pcc_record(crm_create.session, crm.map_crm(answers))
Nov 01 10:34:08 prospector python[218861]:                                    ^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,462: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/local.py", line 143, in __getattr__
Nov 01 10:34:08 prospector python[218861]:     return getattr(self._get_current_object(), name)
Nov 01 10:34:08 prospector python[218861]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,463: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 19, in session
Nov 01 10:34:08 prospector python[218861]:     self._session = crm.get_authorised_session(client)
Nov 01 10:34:08 prospector python[218861]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,463: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apis/crm/crm.py", line 56, in get_authorised_session
Nov 01 10:34:08 prospector python[218861]:     session.fetch_token(**settings)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,463: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 366, in fetch_token
Nov 01 10:34:08 prospector python[218861]:     self._client.parse_request_body_response(r.text, scope=self.scope)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,464: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
Nov 01 10:34:08 prospector python[218861]:     self.token = parse_token_response(body, scope=scope)
Nov 01 10:34:08 prospector python[218861]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,464: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
Nov 01 10:34:08 prospector python[218861]:     validate_token_parameters(params)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,464: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
Nov 01 10:34:08 prospector python[218861]:     raise_from_error(params.get('error'), params)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,465: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
Nov 01 10:34:08 prospector python[218861]:     raise cls(**kwargs)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,465: WARNING/ForkPoolWorker-1] oauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client) AADSTS7000222: The provided client secret keys for app '980db4a8-c6ca-427a-934e-43676ccdfdc8' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: 516aae45-49fb-4756-ba97-5dd6bd380b00 Correlation ID: aeec71bf-8d9c-46cc-9e6f-469df2d4d7aa Timestamp: 2024-11-01 10:34:08Z
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,465: WARNING/ForkPoolWorker-1]
Nov 01 10:34:08 prospector python[218861]: During handling of the above exception, another exception occurred:
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,465: WARNING/ForkPoolWorker-1] Traceback (most recent call last):
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,466: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
Nov 01 10:34:08 prospector python[218861]:     R = retval = fun(*args, **kwargs)
Nov 01 10:34:08 prospector python[218861]:                  ^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,466: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
Nov 01 10:34:08 prospector python[218861]:     return self.run(*args, **kwargs)
Nov 01 10:34:08 prospector python[218861]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,466: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 47, in crm_create
Nov 01 10:34:08 prospector python[218861]:     raise e  # re-raise for celery
Nov 01 10:34:08 prospector python[218861]:     ^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,467: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 44, in crm_create
Nov 01 10:34:08 prospector python[218861]:     result = crm.create_pcc_record(crm_create.new_session, crm.map_crm(answers))
Nov 01 10:34:08 prospector python[218861]:                                    ^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,467: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/local.py", line 143, in __getattr__
Nov 01 10:34:08 prospector python[218861]:     return getattr(self._get_current_object(), name)
Nov 01 10:34:08 prospector python[218861]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,467: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 26, in new_session
Nov 01 10:34:08 prospector python[218861]:     self._session = crm.get_authorised_session(client)
Nov 01 10:34:08 prospector python[218861]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,467: WARNING/ForkPoolWorker-1]   File "/home/plymouth/prospector/prospector/apis/crm/crm.py", line 56, in get_authorised_session
Nov 01 10:34:08 prospector python[218861]:     session.fetch_token(**settings)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,468: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 366, in fetch_token
Nov 01 10:34:08 prospector python[218861]:     self._client.parse_request_body_response(r.text, scope=self.scope)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,468: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
Nov 01 10:34:08 prospector python[218861]:     self.token = parse_token_response(body, scope=scope)
Nov 01 10:34:08 prospector python[218861]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,468: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
Nov 01 10:34:08 prospector python[218861]:     validate_token_parameters(params)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,468: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
Nov 01 10:34:08 prospector python[218861]:     raise_from_error(params.get('error'), params)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,468: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
Nov 01 10:34:08 prospector python[218861]:     raise cls(**kwargs)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,469: WARNING/ForkPoolWorker-1] oauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client) AADSTS7000222: The provided client secret keys for app '980db4a8-c6ca-427a-934e-43676ccdfdc8' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: c942564b-64c2-4427-b25a-2cc466956f00 Correlation ID: 940300de-6c27-4c67-ac8d-23a69b906a3b Timestamp: 2024-11-01 10:34:08Z
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,469: WARNING/ForkPoolWorker-1]
Nov 01 10:34:08 prospector python[218861]: During handling of the above exception, another exception occurred:
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,469: WARNING/ForkPoolWorker-1] Traceback (most recent call last):
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,470: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
Nov 01 10:34:08 prospector python[218861]:     msg = self.format(record)
Nov 01 10:34:08 prospector python[218861]:           ^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,470: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
Nov 01 10:34:08 prospector python[218861]:     return fmt.format(record)
Nov 01 10:34:08 prospector python[218861]:            ^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,470: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/utils/log.py", line 146, in format
Nov 01 10:34:08 prospector python[218861]:     msg = super().format(record)
Nov 01 10:34:08 prospector python[218861]:           ^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,470: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/logging/__init__.py", line 695, in format
Nov 01 10:34:08 prospector python[218861]:     record.exc_text = self.formatException(record.exc_info)
Nov 01 10:34:08 prospector python[218861]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,471: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/utils/log.py", line 142, in formatException
Nov 01 10:34:08 prospector python[218861]:     r = super().formatException(ei)
Nov 01 10:34:08 prospector python[218861]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,471: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/logging/__init__.py", line 645, in formatException
Nov 01 10:34:08 prospector python[218861]:     traceback.print_exception(ei[0], ei[1], tb, None, sio)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,471: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/traceback.py", line 124, in print_exception
Nov 01 10:34:08 prospector python[218861]:     te = TracebackException(type(value), value, tb, limit=limit, compact=True)
Nov 01 10:34:08 prospector python[218861]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,471: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/traceback.py", line 692, in __init__
Nov 01 10:34:08 prospector python[218861]:     self.stack = StackSummary._extract_from_extended_frame_gen(
Nov 01 10:34:08 prospector python[218861]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,472: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/traceback.py", line 416, in _extract_from_extended_frame_gen
Nov 01 10:34:08 prospector python[218861]:     for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,472: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/traceback.py", line 353, in _walk_tb_with_full_positions
Nov 01 10:34:08 prospector python[218861]:     positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
Nov 01 10:34:08 prospector python[218861]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,472: WARNING/ForkPoolWorker-1]   File "/usr/lib/python3.11/traceback.py", line 366, in _get_code_position
Nov 01 10:34:08 prospector python[218861]:     positions_gen = code.co_positions()
Nov 01 10:34:08 prospector python[218861]:                     ^^^^^^^^^^^^^^^^^
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,472: WARNING/ForkPoolWorker-1] AttributeError: '_Code' object has no attribute 'co_positions'
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,472: WARNING/ForkPoolWorker-1] Call stack:
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,482: WARNING/ForkPoolWorker-1]   File "<frozen runpy>", line 198, in _run_module_as_main
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,482: WARNING/ForkPoolWorker-1]   File "<frozen runpy>", line 88, in _run_code
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,482: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/__main__.py", line 19, in <module>
Nov 01 10:34:08 prospector python[218861]:     main()
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,483: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
Nov 01 10:34:08 prospector python[218861]:     sys.exit(_main())
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,483: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/bin/celery.py", line 217, in main
Nov 01 10:34:08 prospector python[218861]:     return celery(auto_envvar_prefix="CELERY")
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,483: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
Nov 01 10:34:08 prospector python[218861]:     return self.main(*args, **kwargs)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,483: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
Nov 01 10:34:08 prospector python[218861]:     rv = self.invoke(ctx)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,484: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
Nov 01 10:34:08 prospector python[218861]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,484: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
Nov 01 10:34:08 prospector python[218861]:     return ctx.invoke(self.callback, **ctx.params)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,484: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
Nov 01 10:34:08 prospector python[218861]:     return __callback(*args, **kwargs)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,484: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
Nov 01 10:34:08 prospector python[218861]:     return f(get_current_context(), *args, **kwargs)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,485: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
Nov 01 10:34:08 prospector python[218861]:     return f(ctx, *args, **kwargs)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,485: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/bin/worker.py", line 351, in worker
Nov 01 10:34:08 prospector python[218861]:     worker.start()
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,485: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/worker/worker.py", line 203, in start
Nov 01 10:34:08 prospector python[218861]:     self.blueprint.start(self)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,485: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
Nov 01 10:34:08 prospector python[218861]:     step.start(parent)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,485: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
Nov 01 10:34:08 prospector python[218861]:     return self.obj.start()
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,486: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/concurrency/base.py", line 129, in start
Nov 01 10:34:08 prospector python[218861]:     self.on_start()
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,486: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/concurrency/prefork.py", line 109, in on_start
Nov 01 10:34:08 prospector python[218861]:     P = self._pool = Pool(processes=self.limit,
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,486: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 463, in __init__
Nov 01 10:34:08 prospector python[218861]:     super().__init__(processes, *args, **kwargs)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,486: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/pool.py", line 1046, in __init__
Nov 01 10:34:08 prospector python[218861]:     self._create_worker_process(i)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,486: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 480, in _create_worker_process
Nov 01 10:34:08 prospector python[218861]:     return super()._create_worker_process(i)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,487: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/pool.py", line 1158, in _create_worker_process
Nov 01 10:34:08 prospector python[218861]:     w.start()
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,487: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/process.py", line 124, in start
Nov 01 10:34:08 prospector python[218861]:     self._popen = self._Popen(self)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,487: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/context.py", line 333, in _Popen
Nov 01 10:34:08 prospector python[218861]:     return Popen(process_obj)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,487: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/popen_fork.py", line 24, in __init__
Nov 01 10:34:08 prospector python[218861]:     self._launch(process_obj)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,487: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/popen_fork.py", line 79, in _launch
Nov 01 10:34:08 prospector python[218861]:     code = process_obj._bootstrap()
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,488: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/process.py", line 327, in _bootstrap
Nov 01 10:34:08 prospector python[218861]:     self.run()
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,488: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/process.py", line 114, in run
Nov 01 10:34:08 prospector python[218861]:     self._target(*self._args, **self._kwargs)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,488: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/pool.py", line 292, in __call__
Nov 01 10:34:08 prospector python[218861]:     sys.exit(self.workloop(pid=pid))
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,488: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/billiard/pool.py", line 362, in workloop
Nov 01 10:34:08 prospector python[218861]:     result = (True, prepare_result(fun(*args, **kwargs)))
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,488: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 649, in fast_trace_task
Nov 01 10:34:08 prospector python[218861]:     R, I, T, Rstr = tasks[task].__trace__(
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,489: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 468, in trace_task
Nov 01 10:34:08 prospector python[218861]:     I, R, state, retval = on_error(task_request, exc, uuid)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,489: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 379, in on_error
Nov 01 10:34:08 prospector python[218861]:     R = I.handle_error_state(
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,489: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 178, in handle_error_state
Nov 01 10:34:08 prospector python[218861]:     return {
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,489: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 237, in handle_failure
Nov 01 10:34:08 prospector python[218861]:     self._log_error(task, req, einfo)
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,489: WARNING/ForkPoolWorker-1]   File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 265, in _log_error
Nov 01 10:34:08 prospector python[218861]:     logger.log(policy.severity, policy.format.strip(), context,
Nov 01 10:34:08 prospector python[218861]: [2024-11-01 10:34:08,490: WARNING/ForkPoolWorker-1] Message: 'Task %(name)s[%(id)s] %(description)s: %(exc)s'
Nov 01 10:34:08 prospector python[218861]: Arguments: {'hostname': 'celery@prospector', 'id': 'f5f2b406-77eb-4eb3-97e2-4ee1628b9e42', 'name': 'prospector.apps.crm.tasks.crm_create', 'exc': 'InvalidClientError("(invalid_client) AADSTS7000222: The provided client secret keys for app \'980db4a8-c6ca-427a-934e-43676ccdfdc8\' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: c942564b-64c2-4427-b25a-2cc466956f00 Correlation ID: 940300de-6c27-4c67-ac8d-23a69b906a3b Timestamp: 2024-11-01 10:34:08Z")', 'traceback': 'Traceback (most recent call last):\n  File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 40, in crm_create\n    result = crm.create_pcc_record(crm_create.session, crm.map_crm(answers))\n                                   ^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/venv/lib/python3.11/site-packages/celery/local.py", line 143, in __getattr__\n    return getattr(self._get_current_object(), name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 19, in session\n    self._session = crm.get_authorised_session(client)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/prospector/prospector/apis/crm/crm.py", line 56, in get_authorised_session\n    session.fetch_token(**settings)\n  File "/home/plymouth/venv/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 366, in fetch_token\n    self._client.parse_request_body_response(r.text, scope=self.scope)\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response\n    self.token = parse_token_response(body, scope=scope)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response\n    validate_token_parameters(params)\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters\n    raise_from_error(params.get(\'error\'), params)\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error\n    raise cls(**kwargs)\noauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client) AADSTS7000222: The provided client secret keys for app \'980db4a8-c6ca-427a-934e-43676ccdfdc8\' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: 516aae45-49fb-4756-ba97-5dd6bd380b00 Correlation ID: aeec71bf-8d9c-46cc-9e6f-469df2d4d7aa Timestamp: 2024-11-01 10:34:08Z\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/venv/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 47, in crm_create\n    raise e  # re-raise for celery\n    ^^^^^^^\n  File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 44, in crm_create\n    result = crm.create_pcc_record(crm_create.new_session, crm.map_crm(answers))\n                                   ^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/venv/lib/python3.11/site-packages/celery/local.py", line 143, in __getattr__\n    return getattr(self._get_current_object(), name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/prospector/prospector/apps/crm/tasks.py", line 26, in new_session\n    self._session = crm.get_authorised_session(client)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/prospector/prospector/apis/crm/crm.py", line 56, in get_authorised_session\n    session.fetch_token(**settings)\n  File "/home/plymouth/venv/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 366, in fetch_token\n    self._client.parse_request_body_response(r.text, scope=self.scope)\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response\n    self.token = parse_token_response(body, scope=scope)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response\n    validate_token_parameters(params)\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters\n    raise_from_error(params.get(\'error\'), params)\n  File "/home/plymouth/venv/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error\n    raise cls(**kwargs)\noauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client) AADSTS7000222: The provided client secret keys for app \'980db4a8-c6ca-427a-934e-43676ccdfdc8\' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: c942564b-64c2-4427-b25a-2cc466956f00 Correlation ID: 940300de-6c27-4c67-ac8d-23a69b906a3b Timestamp: 2024-11-01 10:34:08Z\n', 'args': "['a718a9de-895f-41a2-86ea-1212eac24da7']", 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}
Nov 01 10:34:10 prospector python[218853]: [2024-11-01 10:34:10,047: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '7ace7198-7181-3cf9-b2a6-6787ac0647c2'} ticket:84bc4e87-d98e-46d0-83f0-70a87c9f03d1]
Nov 01 10:34:12 prospector python[218853]: [2024-11-01 10:34:12,209: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '04777509-fc73-3a54-a04b-b0e1bc0dfa0a'} ticket:9b1ebd43-43d1-4056-a3ea-5a431ae7e3fa]
Nov 01 10:34:14 prospector python[218853]: [2024-11-01 10:34:14,531: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '1656f204-1944-3ed3-98be-db2fc3cfda8b'} ticket:b28a89b9-f1d4-42fb-a5c7-a4ec7123207c]
Nov 01 10:34:17 prospector python[218853]: [2024-11-01 10:34:17,022: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'c5ddf977-18b0-39c8-8641-411ba066d1db'} ticket:42d8f0b6-14a1-45ba-8dc1-7ebaafb27206]
Nov 01 10:34:19 prospector python[218853]: [2024-11-01 10:34:19,157: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '61cff0ca-22f8-31f8-a862-c84edb329f57'} ticket:fe6072c1-9cc4-404c-bb00-285d23a747a3]
Nov 01 10:34:21 prospector python[218853]: [2024-11-01 10:34:21,800: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'f51ce05b-6da4-30b4-81ab-9aa9158c2f21'} ticket:abf62201-555f-4c2f-9085-0f3076bc19e7]
Nov 01 10:34:23 prospector python[218853]: [2024-11-01 10:34:23,882: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '3d88dc30-bf66-3fd6-91f6-2accaedc2e80'} ticket:5887ecf4-1c88-4d6f-a009-a2353b1eee39]
Nov 01 10:34:26 prospector python[218853]: [2024-11-01 10:34:26,162: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'bdb27856-fafd-3c5e-a1c3-3a4b7da31219'} ticket:1441468e-cd98-4fd0-984e-5f4035d6223a]
Nov 01 10:34:28 prospector python[218853]: [2024-11-01 10:34:28,440: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '26f5daac-9e4a-31d4-80d7-2316d2ae031a'} ticket:d27da932-4f00-4a2c-86c9-78ee1fa0d892]
Nov 01 10:34:30 prospector python[218853]: [2024-11-01 10:34:30,634: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'b1988f0a-2c1c-3cc7-9658-4ac5c6eb7e8b'} ticket:c4d3b51c-055e-4dc3-b30d-081053707f83]
Nov 01 10:34:32 prospector python[218853]: [2024-11-01 10:34:32,997: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'cc75a662-ba2e-3607-a1f5-e0a2b44e352c'} ticket:d1dd03d2-4e47-4265-b770-588ed04770a9]
Nov 01 10:34:35 prospector python[218853]: [2024-11-01 10:34:35,242: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'bee85b83-3fea-3c0c-be47-38021fef9e76'} ticket:2fe94fca-b374-4d2f-a419-006bc1ec595f]
Nov 01 10:34:37 prospector python[218853]: [2024-11-01 10:34:37,389: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '0411b72d-4851-3dfc-bb50-530fa40f20c9'} ticket:3e7bd723-a3dc-415a-89ba-64728e9094df]
Nov 01 10:34:39 prospector python[218853]: [2024-11-01 10:34:39,658: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '44ef3a61-6909-3222-b05b-b4cb22e99302'} ticket:665717b2-fda7-4d2d-ad67-a38f2c6629d1]
Nov 01 10:34:41 prospector python[218853]: [2024-11-01 10:34:41,870: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '4eec4811-be6c-3a2c-a531-728d0b1a26d5'} ticket:d36b9aad-4dab-4740-a573-d7fa47d375e3]
Nov 01 10:34:44 prospector python[218853]: [2024-11-01 10:34:44,168: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '2dcfd026-f2b3-32ea-bfec-008509792be3'} ticket:dd71ee50-2318-4fb5-9af5-deca9a8b7c81]
Nov 01 10:34:46 prospector python[218853]: [2024-11-01 10:34:46,408: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'ab595a2b-0c6a-331f-bfea-863f37c6676d'} ticket:a108759a-0f7c-470a-998d-4b9ed46cd21d]
Nov 01 10:34:48 prospector python[218853]: [2024-11-01 10:34:48,687: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '1140a16c-ad5d-358d-a24a-35228ce01ff2'} ticket:b7eac2bb-f845-4c2b-8a84-8a7799566580]
Nov 01 10:34:50 prospector python[218853]: [2024-11-01 10:34:50,946: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '5bace668-211a-3be2-a1b3-e0fd04ea67aa'} ticket:99751d47-a68c-4c41-865d-19c4b04557d8]
Nov 01 10:34:53 prospector python[218853]: [2024-11-01 10:34:53,187: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'ac0890ac-b042-3116-bda8-7102f83e4e86'} ticket:10242109-1803-4aa8-8818-5c0b9be26c97]
Nov 01 10:34:55 prospector python[218853]: [2024-11-01 10:34:55,339: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '226dc0f7-c41b-385e-8ec0-bb443c3663de'} ticket:c855ef5f-b1ad-4ad9-9ce9-b08a57268a0f]
Nov 01 10:34:57 prospector python[218853]: [2024-11-01 10:34:57,474: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '6e9dfda0-2b0a-3466-bb58-a2bbe4e7d454'} ticket:2babc503-22f6-45b9-8de8-7da264cd92a1]
Nov 01 10:34:59 prospector python[218853]: [2024-11-01 10:34:59,593: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '4e42c9fe-1f6f-3c8c-87ed-2757de81de1e'} ticket:708813f2-0f20-4312-b206-a436b3a731cd]
Nov 01 10:35:01 prospector python[218853]: [2024-11-01 10:35:01,729: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'a7e9058c-fa9e-3ce7-9d0e-18d1befe3eb7'} ticket:99983c1b-874a-4052-9893-69326b42e2ce]
Nov 01 10:35:04 prospector python[218853]: [2024-11-01 10:35:04,233: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '1bd99f30-2237-3371-9acb-a73e6dd2feae'} ticket:6358f629-5ce3-438b-b578-0b7849712329]
Nov 01 10:35:06 prospector python[218853]: [2024-11-01 10:35:06,373: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'c05c0c95-a691-3d4c-b913-dafb4a574906'} ticket:e447a85d-1510-4a7c-bed9-97d091444c52]
Nov 01 10:35:08 prospector python[218853]: [2024-11-01 10:35:08,515: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '01d45630-b7b8-3cfa-98b9-72fbdbd65043'} ticket:cd1c44c5-627f-4842-b203-24e36cf6901f]
Nov 01 10:35:10 prospector python[218853]: [2024-11-01 10:35:10,669: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '22d6a144-77d1-3aef-9928-48c04ba2da9a'} ticket:e01971a3-3332-4dd0-b1af-decd77f06d3c]
Nov 01 10:35:12 prospector python[218853]: [2024-11-01 10:35:12,835: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '90cf4e4b-6355-339e-a352-954c1e5f7de8'} ticket:494755de-b34d-4e99-8af0-a784ba1e9466]
Nov 01 10:35:14 prospector python[218853]: [2024-11-01 10:35:14,826: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '70d17832-1025-3637-9178-0365a83f0032'} ticket:1fec1e29-e390-4d5d-8918-c5ff4bb7686c]
Nov 01 10:35:16 prospector python[218853]: [2024-11-01 10:35:16,835: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '8bc95473-ab98-3c2c-a5d0-11cdd32be184'} ticket:aa37d832-3167-421f-93e7-c8faba32b9f2]
Nov 01 10:35:18 prospector python[218853]: [2024-11-01 10:35:18,873: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '305dfbdb-71d7-3a68-bf81-c898205ba10a'} ticket:05dc2127-fd7c-4fc7-9aea-25fbe5a2906d]
Nov 01 10:35:20 prospector python[218853]: [2024-11-01 10:35:20,893: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '3319e534-4a96-30a9-afb5-b9ad3c8bb6f3'} ticket:0ed64bc0-3af1-40a0-8163-c7728f1749e2]
Nov 01 10:35:23 prospector python[218853]: [2024-11-01 10:35:23,103: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '1f9874a8-bc9a-379a-9f7c-d51ccae11375'} ticket:7b46d493-2129-412b-bb63-95a6cfe375fd]
Nov 01 10:35:25 prospector python[218853]: [2024-11-01 10:35:25,066: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'd8061ef0-7ea8-3258-9d6b-7bbb203b07a2'} ticket:92ba966b-5828-42bd-95e8-9908d3377e83]
Nov 01 10:35:27 prospector python[218853]: [2024-11-01 10:35:27,140: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '7e6a4997-712e-38ef-bdc8-d1238eaec5c8'} ticket:5f3c95e4-d22f-41ec-a8b1-02b38d8ea572]
Nov 01 10:35:29 prospector python[218853]: [2024-11-01 10:35:29,506: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '11acc1d2-d6b0-39b6-850d-af303efb3ec0'} ticket:6849fea1-dbf0-4a2e-be73-77d8f06e6183]
Nov 01 10:35:31 prospector python[218853]: [2024-11-01 10:35:31,730: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'fffcf5ad-8991-3e07-8051-b5f98d02a0e3'} ticket:0ba715f0-65ec-4b96-9948-20a35bf93b2a]
Nov 01 10:35:33 prospector python[218853]: [2024-11-01 10:35:33,888: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '104cfd43-7716-3a0e-ad40-38717080cdf0'} ticket:c5dc1057-c108-4779-ba07-1979bad19aae]
Nov 01 10:35:36 prospector python[218853]: [2024-11-01 10:35:36,129: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'f252948c-4ce7-390b-9e59-46944d8cf653'} ticket:0c10f010-cd14-4b9a-8dc5-67a06f9efe63]
Nov 01 10:35:38 prospector python[218853]: [2024-11-01 10:35:38,125: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'dce4ce3c-784e-3c0c-b2e0-9778a9fa0024'} ticket:80d8814f-30a6-4419-b74e-5b4dffa85ad1]
Nov 01 10:35:40 prospector python[218853]: [2024-11-01 10:35:40,410: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '9b63a747-5ef9-3446-b714-ff1fefac3a5b'} ticket:249639fc-7547-4192-8868-096a4bbfa090]
Nov 01 10:35:42 prospector python[218853]: [2024-11-01 10:35:42,795: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '58c1cf34-a0e5-3d1e-b57b-e7fd98d82edb'} ticket:9e81c67b-3806-4922-aa68-38f98a1b3b84]
Nov 01 10:35:44 prospector python[218853]: [2024-11-01 10:35:44,971: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '21c2fe4e-3f1b-38e1-ab77-662951a7c58f'} ticket:0af44068-6cd0-4cac-b612-d4fcc9ee7324]
Nov 01 10:35:47 prospector python[218853]: [2024-11-01 10:35:47,251: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'e71a9524-c03c-3136-982e-5570dfe5732c'} ticket:e97bb5b1-8665-4067-8dea-66f912d2a164]
Nov 01 10:35:49 prospector python[218853]: [2024-11-01 10:35:49,340: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '1e4b8c69-c500-3259-ac6d-a0db74f92999'} ticket:e3b8eea3-ddd7-4bfd-bcb0-a6410829fbb7]
Nov 01 10:35:51 prospector python[218853]: [2024-11-01 10:35:51,318: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '622f93d4-84bb-3157-bdbf-6f38ea59aacf'} ticket:d1e91af7-0e91-4f88-bb89-39ac879797dc]
Nov 01 10:35:53 prospector python[218853]: [2024-11-01 10:35:53,363: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '9fc79769-55b6-373b-b267-3583f77b2d43'} ticket:7ecc71e1-b620-4162-8e57-b9b8b8c0b78a]
Nov 01 10:35:55 prospector python[218853]: [2024-11-01 10:35:55,628: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'fddb9431-aaa8-372f-a708-49b423a9c2ad'} ticket:e9670a53-7bca-4a35-8f14-e97dbf043d4a]
Nov 01 10:35:58 prospector python[218853]: [2024-11-01 10:35:58,000: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'ae06de08-c9ef-3775-bc79-79b04bfd6b67'} ticket:15fb78f2-557e-49db-b520-471b1582c1b7]
Nov 01 10:36:00 prospector python[218853]: [2024-11-01 10:36:00,155: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '17000352-7006-3802-bce5-c581049d996a'} ticket:c0fcbd3d-e4d0-41c4-b409-399673e7877a]
Nov 01 10:36:02 prospector python[218853]: [2024-11-01 10:36:02,676: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '683d3760-10d2-3fc7-baf9-e7d1f49d55bc'} ticket:92f28f13-7bc1-4fbc-bad9-e7c51242ac4e]
Nov 01 10:36:04 prospector python[218853]: [2024-11-01 10:36:04,998: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '7989f29e-de28-3a7d-aa7c-bf7b01ac751f'} ticket:34185e6b-c529-4978-9334-853a3a9a9ab1]
Nov 01 10:36:07 prospector python[218853]: [2024-11-01 10:36:07,204: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '26f90ec8-4610-36f8-a105-51c33766a1a0'} ticket:2f225ef4-62de-4c72-ab2d-fa445891b5a2]
Nov 01 10:36:09 prospector python[218853]: [2024-11-01 10:36:09,515: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '4a093d0a-df09-31f3-8319-4ae6ed4ecdc7'} ticket:25a16e80-c3cc-4414-b66f-f0aecf6470a9]
Nov 01 10:36:11 prospector python[218853]: [2024-11-01 10:36:11,751: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '913b6fd3-cc54-3b42-a392-68669964ee7b'} ticket:a168d348-14d2-4231-86dc-0ab0a503a3f3]
Nov 01 10:36:14 prospector python[218853]: [2024-11-01 10:36:14,109: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '5a1b7c11-7360-3a85-bc5e-424b197c9d6d'} ticket:7438e1cb-8e6f-495f-80bd-a9e8b23fdb81]
Nov 01 10:36:16 prospector python[218853]: [2024-11-01 10:36:16,613: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '3f71f941-defa-3e16-af63-165e0e992a6f'} ticket:608a70b5-a70f-42cd-8a92-ad649c533111]
Nov 01 10:36:18 prospector python[218853]: [2024-11-01 10:36:18,965: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '948c96a7-6bc9-330b-aa01-d4e444732833'} ticket:99d40dd8-ec65-447c-a0ce-1e8c2796df29]
Nov 01 10:36:21 prospector python[218853]: [2024-11-01 10:36:21,213: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '42cbf1f0-01de-3726-a967-8bcd09e07754'} ticket:0559309c-e519-4a10-8e0c-c792d8b16a2f]
Nov 01 10:36:23 prospector python[218853]: [2024-11-01 10:36:23,470: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'b9523b2f-8824-3289-9ccd-e93560ac95bf'} ticket:7b0dcdb7-1c6a-43a6-9c46-c4f9ec717c87]
Nov 01 10:36:25 prospector python[218853]: [2024-11-01 10:36:25,715: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '2da2bc76-8ff9-3330-bd2b-e8060294bf20'} ticket:890bd440-9a8d-43c3-afaa-4be3a32d11cb]
Nov 01 10:36:28 prospector python[218853]: [2024-11-01 10:36:28,018: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '1f900a0e-6d4c-33b1-9be1-63f51ade7c78'} ticket:fe32e426-f349-47f3-96e3-efe47c04111a]
Nov 01 10:36:30 prospector python[218853]: [2024-11-01 10:36:30,222: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '3323df16-f6e0-37a1-81c2-a45142eef2ea'} ticket:15b2d58b-1fa3-43b3-9141-a722298cc7ad]
Nov 01 10:36:32 prospector python[218853]: [2024-11-01 10:36:32,395: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '7428d722-dbae-3b3c-b502-5e6b900ed648'} ticket:908c621e-7f85-40c8-979d-326ec7e00193]
Nov 01 10:36:34 prospector python[218853]: [2024-11-01 10:36:34,683: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '959d8b51-414d-353e-8833-46a0ebda29c4'} ticket:568d8e4f-a31d-4868-a645-6fc8ac6e04cb]
Nov 01 10:36:36 prospector python[218853]: [2024-11-01 10:36:36,945: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'd655a5fc-d649-3c8f-a9bf-5bb993fcdeb3'} ticket:13a003c8-6647-4c57-9c5d-ffffdb8cfbd3]
Nov 01 10:36:39 prospector python[218853]: [2024-11-01 10:36:39,115: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '298e0cc7-86b2-3e52-b9d7-53c133df2e5a'} ticket:2d41f725-5fee-4071-872e-1cf5e7efafe0]
Nov 01 10:36:41 prospector python[218853]: [2024-11-01 10:36:41,582: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'aac32b52-4ff9-3c6b-9796-a9c08c045ba6'} ticket:69a23c63-6116-452f-b715-052da551d3b1]
Nov 01 10:36:43 prospector python[218853]: [2024-11-01 10:36:43,991: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '1f522da6-a304-327c-b40e-22361f6a167c'} ticket:7737aa62-c7d5-403a-8921-e9734d6bd2b7]
Nov 01 10:36:46 prospector python[218853]: [2024-11-01 10:36:46,184: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '251ca476-9d60-33ad-b6e2-a2b47322fd2f'} ticket:584b96be-d8ae-403b-8aac-85cc253e3b20]
Nov 01 10:36:48 prospector python[218853]: [2024-11-01 10:36:48,452: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'ca7f2f23-0e96-376b-9a4d-9c5c3b24120a'} ticket:d5f861a8-3179-4186-9be6-4c8ea35ca1d7]
Nov 01 10:36:50 prospector python[218853]: [2024-11-01 10:36:50,622: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '4f3607d5-d6ee-3565-9b6f-0ad1ee0e321d'} ticket:80ffd84b-7653-4ed0-bc0a-509d42833867]
Nov 01 10:36:52 prospector python[218853]: [2024-11-01 10:36:52,865: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '23e3bb90-8406-34a9-bda2-e46e5805e2c7'} ticket:b51db0a4-c768-4826-90a4-84cccc5c37e7]
Nov 01 10:36:55 prospector python[218853]: [2024-11-01 10:36:55,151: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'a34f9c05-fe94-322f-a8dc-3e9b23c6ac69'} ticket:a1878bdd-71d9-4973-97f5-c328c1f3387d]
Nov 01 10:36:57 prospector python[218853]: [2024-11-01 10:36:57,417: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '200bf459-8bb7-3b79-9a10-dfe21211fd91'} ticket:16aa21e7-62c8-4ec4-a7c6-ef5765e2c394]
Nov 01 10:36:59 prospector python[218853]: [2024-11-01 10:36:59,751: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '3582a6ef-004f-3179-9a29-0abdc3b065b7'} ticket:2c7e4d3d-7fc0-4246-883c-58bfe30eebaf]
Nov 01 10:37:02 prospector python[218853]: [2024-11-01 10:37:02,025: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'e9162872-ae41-3325-844d-86e4ab10ec26'} ticket:d59138a6-0ccb-4919-a848-10c373cefa50]
Nov 01 10:37:04 prospector python[218853]: [2024-11-01 10:37:04,366: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '3cd97926-b5bc-3124-b68a-fdbe8a5c2c05'} ticket:8b18d584-f996-49d5-a62c-b23736e289cb]
Nov 01 10:37:06 prospector python[218853]: [2024-11-01 10:37:06,760: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '35f1f18e-e02f-3f52-bcbf-5325a395af42'} ticket:133c5492-1668-441b-a499-065c21b59bc0]
Nov 01 10:37:09 prospector python[218853]: [2024-11-01 10:37:09,239: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'bf359265-fba6-3bee-9f2f-f6cc36d54308'} ticket:d6b7b5cd-637f-40fd-be83-8e5b3d84f1ae]
Nov 01 10:37:11 prospector python[218853]: [2024-11-01 10:37:11,511: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '40fe6f1b-3a5f-3786-b8ee-d3e430e7c9db'} ticket:b24812d2-1f83-4386-999c-acbcbcdb0e34]
Nov 01 10:37:13 prospector python[218853]: [2024-11-01 10:37:13,767: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '9f6eb64a-4d7d-387b-a93c-0977cc90d2a7'} ticket:60f9d2a0-ccb8-4334-95d7-f1956d119ce8]
Nov 01 10:37:16 prospector python[218853]: [2024-11-01 10:37:16,125: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'e13ceccf-4d8b-3c86-a8f9-2b5a49572db8'} ticket:4563e6eb-7550-47e6-8602-2d09e4781fb4]
Nov 01 10:37:18 prospector python[218853]: [2024-11-01 10:37:18,562: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '23700827-9227-3658-b5c2-60cefe8300f4'} ticket:fa2775f8-dfed-4831-8a7a-fc591df5794f]
Nov 01 10:37:20 prospector python[218853]: [2024-11-01 10:37:20,868: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '22e91927-de2b-3732-9d4e-f7a2e6d4479b'} ticket:f2bd232d-db58-419c-837c-6ebf68d49c1e]
Nov 01 10:37:23 prospector python[218853]: [2024-11-01 10:37:23,164: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '3e5e18d1-1a42-3eee-bcea-e599d0b6e43e'} ticket:f1059260-b326-44cb-b79d-52a0ed923a1d]
Nov 01 10:37:25 prospector python[218853]: [2024-11-01 10:37:25,378: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '9b44af17-e8a7-3bcc-8c01-0fd9643de5a2'} ticket:3ec194eb-5809-4a6e-b99d-a9bd42fc4e86]
Nov 01 10:37:27 prospector python[218853]: [2024-11-01 10:37:27,604: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '6ebb1ba8-c4ee-3ac6-ae01-71f8ff5fa171'} ticket:f5749299-2f5c-4056-8dfc-198f5cd83543]
Nov 01 10:37:29 prospector python[218853]: [2024-11-01 10:37:29,545: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'aaec2c2c-2bc8-3ac8-b34d-9e6c3abf41cf'} ticket:5c479b8a-6ef5-4baf-bdb1-a363eaf3156d]
Nov 01 10:37:31 prospector python[218853]: [2024-11-01 10:37:31,568: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '04b1f8e2-96b6-3312-9857-5a0425fc05d8'} ticket:77dba14b-ffce-48cb-8dc9-067cb70dd280]
Nov 01 10:37:33 prospector python[218853]: [2024-11-01 10:37:33,547: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'cefbc0a9-885f-3095-8394-47b1597ba5ce'} ticket:35971a86-1b34-46ea-bcbb-ff1b0e32a84f]
Nov 01 10:37:35 prospector python[218853]: [2024-11-01 10:37:35,588: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'cc820928-06a6-3333-8b80-1deae909118d'} ticket:79488728-7141-4346-b1f8-0271b616fea0]
Nov 01 10:37:37 prospector python[218853]: [2024-11-01 10:37:37,621: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '266e5fa4-9b7e-356e-9a8c-350cfe4de528'} ticket:ddf9298a-0e84-4653-ad72-b4a341461ddd]
Nov 01 10:37:39 prospector python[218853]: [2024-11-01 10:37:39,613: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'dda7d165-6ba3-366b-8c58-e65d1dc1db2d'} ticket:82c56b67-bdec-445b-b731-53273bdc0b95]
Nov 01 10:37:41 prospector python[218853]: [2024-11-01 10:37:41,685: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '89ab9c6e-84ad-3624-a000-4977c28f8f24'} ticket:029ad30c-b6d5-47f4-a89c-c8b0c8fd95c6]
Nov 01 10:37:43 prospector python[218853]: [2024-11-01 10:37:43,808: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'f695ff1c-fc54-320e-9675-28abce1dc98e'} ticket:9d05db0a-2ced-4509-b239-26afbb47ba68]
Nov 01 10:37:45 prospector python[218853]: [2024-11-01 10:37:45,939: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'fab38a60-2c7b-3e36-8e57-f03aa0f298b9'} ticket:7fec48ab-19af-4f00-8c30-d23d28cbaede]
Nov 01 10:37:48 prospector python[218853]: [2024-11-01 10:37:48,019: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'c1c31a63-4d24-3ecc-8904-2ebd6f3d6fba'} ticket:6209502b-7213-4a7c-a4c3-ffe22d850d86]
Nov 01 10:37:50 prospector python[218853]: [2024-11-01 10:37:50,047: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '412b7e0a-9397-3415-8034-ffd9066877ca'} ticket:221fd3d9-d0a2-4d73-8b88-31df2164666a]
Nov 01 10:37:52 prospector python[218853]: [2024-11-01 10:37:52,037: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '01c47d30-cd3d-3c58-9ea7-05951de39dea'} ticket:84e2b025-0fd8-4768-a955-6ce62943494a]
Nov 01 10:37:54 prospector python[218853]: [2024-11-01 10:37:54,084: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'e6ee542b-04e0-3667-9e27-84a20e30147d'} ticket:8f3cf5f1-3443-45b4-82a2-6e21e53278a8]
Nov 01 10:37:56 prospector python[218853]: [2024-11-01 10:37:56,048: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '62112af6-75af-369d-9972-0efa5327e04b'} ticket:975084a0-4062-4429-90a6-ecc4ef883c35]
Nov 01 10:37:58 prospector python[218853]: [2024-11-01 10:37:58,274: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'a138c1ab-b426-3886-beab-e41dce7a979a'} ticket:68875b28-6a1f-4597-81c9-d7c0df769173]
Nov 01 10:38:00 prospector python[218853]: [2024-11-01 10:38:00,552: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '7fe5b5f5-c2bf-3111-afe3-b94b9af68638'} ticket:bfb77e28-8d65-4138-822a-2fc33ace616f]
Nov 01 10:38:02 prospector python[218853]: [2024-11-01 10:38:02,651: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'aa51f9ca-4ec6-3a3a-bc09-08cb81f85b1c'} ticket:86256d99-d178-42c6-bf59-a7e0149ac8c2]
Nov 01 10:38:04 prospector python[218853]: [2024-11-01 10:38:04,928: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'a8eeaecc-f4af-3143-8f3d-8bdcf260c0a4'} ticket:8f7b7a4d-5b8f-4a32-b0cc-640ac301f2fe]
Nov 01 10:38:07 prospector python[218853]: [2024-11-01 10:38:07,109: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '46b1f6e1-56f4-3fa7-be09-79485116cc22'} ticket:7dd4df81-f487-419e-ab79-723f3f1d5360]
Nov 01 10:38:09 prospector python[218853]: [2024-11-01 10:38:09,337: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '978ebb75-8739-3e49-9024-b1c4fccd6474'} ticket:b9e3c499-dabd-4662-b201-c38c077d90de]
Nov 01 10:38:11 prospector python[218853]: [2024-11-01 10:38:11,342: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '64a402a8-87e4-3775-af79-2affe301e8e6'} ticket:95ace83c-2618-4154-8ee4-d88513ea0b68]
Nov 01 10:38:13 prospector python[218853]: [2024-11-01 10:38:13,515: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '9a5ec1ea-2f27-347a-b8e6-eeea5b97c5ff'} ticket:dfa69d34-7e5c-402e-9a74-585699edcc6d]
Nov 01 10:38:15 prospector python[218853]: [2024-11-01 10:38:15,652: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'cf89b9aa-f4fb-3504-81c4-038d8c678ec2'} ticket:950d832a-ce1c-40f9-85d0-5ad15429e64b]
Nov 01 10:38:17 prospector python[218853]: [2024-11-01 10:38:17,828: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '056b0b81-8474-349e-846b-8bce28c8b149'} ticket:ee8fc9c3-d09b-4b5b-93f3-d32534e1d311]
Nov 01 10:38:19 prospector python[218853]: [2024-11-01 10:38:19,911: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '12b95382-ce35-3f02-aec2-d08130c15415'} ticket:491c47a9-ec36-4118-a5d4-7c2be4b9f873]
Nov 01 10:38:22 prospector python[218853]: [2024-11-01 10:38:22,077: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '98fb02a2-6142-3969-8fee-12c167221915'} ticket:3086eaab-e519-42d9-961e-d535989945aa]
Nov 01 10:38:24 prospector python[218853]: [2024-11-01 10:38:24,052: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'afaba99d-8f74-3201-9801-94696f67240e'} ticket:630c100a-aa8a-4710-9cc5-0ec7c458d4ff]
Nov 01 10:38:26 prospector python[218853]: [2024-11-01 10:38:26,145: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '316b82b5-fad5-3cce-acfd-5067291acf02'} ticket:e7e7e17a-05a2-410b-9493-a11b17c46d5a]
Nov 01 10:38:28 prospector python[218853]: [2024-11-01 10:38:28,623: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '69e89541-ec6b-3848-adf3-38394ee2be5f'} ticket:56df09eb-df15-451c-b165-ef94d6ed5231]
Nov 01 10:38:30 prospector python[218853]: [2024-11-01 10:38:30,913: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '2c97e943-4b99-3e77-a38e-bc0bd17cdce0'} ticket:b8d4956e-41a6-41d0-95f9-90e6df296ae8]
Nov 01 10:38:33 prospector python[218853]: [2024-11-01 10:38:33,160: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'cd106a27-00f6-3721-8e11-894cdd4a800e'} ticket:ecb51a42-91c9-4f2f-a148-b0010bafd950]
Nov 01 10:38:35 prospector python[218853]: [2024-11-01 10:38:35,419: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '0626ee9e-15f3-314b-8240-fab7bf441e08'} ticket:769f7313-0d74-4bf6-a5f7-cf40f7012b2e]
Nov 01 10:38:37 prospector python[218853]: [2024-11-01 10:38:37,735: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'c93b5b90-8c32-398e-ba56-899c68efb069'} ticket:fd6efa4b-9d43-4ff2-b9e8-d14017eee825]
Nov 01 10:38:39 prospector python[218853]: [2024-11-01 10:38:39,942: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '8f8a0b42-9e29-3336-b72c-ac32164479a5'} ticket:9c089c50-adb2-4814-857e-3df1e06edd31]
Nov 01 10:38:42 prospector python[218853]: [2024-11-01 10:38:42,130: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '844ca09f-d8a8-345f-8f3c-d36f846d5983'} ticket:a5b9d0a1-ace1-4524-bae7-73f1135ca55a]
Nov 01 10:38:44 prospector python[218853]: [2024-11-01 10:38:44,469: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '7ba9418c-250d-31d7-b3dc-fcf794af1134'} ticket:5c40b68f-c861-43d1-920c-0375d37263c8]
Nov 01 10:38:46 prospector python[218853]: [2024-11-01 10:38:46,665: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '305060e4-ab2c-3891-b9dd-5785b582b98f'} ticket:7e01e4f6-f218-4b7f-8c0a-d54e6b1e08d2]
Nov 01 10:38:48 prospector python[218853]: [2024-11-01 10:38:48,998: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'c51d2e50-1874-35ce-bd8f-a78732fb0a49'} ticket:54823c4c-85f2-41e8-b558-65165e92820a]
Nov 01 10:38:51 prospector python[218853]: [2024-11-01 10:38:51,191: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'cbe73a50-fb15-3d94-9c86-db64c7fce60f'} ticket:bbda8cd7-a1b7-4370-bacb-7a3da7f9b9fa]
Nov 01 10:38:53 prospector python[218853]: [2024-11-01 10:38:53,461: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '70231d8a-1855-3ae1-b00f-17a329982066'} ticket:85271e5c-f60f-44e4-86d0-f387cd384514]
Nov 01 10:38:55 prospector python[218853]: [2024-11-01 10:38:55,867: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '461e3bae-f96d-30b9-a75c-6332e8eb0d27'} ticket:9c15fdab-7d14-4bfc-a51a-f026f955d3fd]
Nov 01 10:38:58 prospector python[218853]: [2024-11-01 10:38:58,228: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'a380eef7-eaf6-3a19-a5d3-19ac6c7987ed'} ticket:d09ec73f-a6f8-47eb-87a4-00de25d85e0c]
Nov 01 10:39:00 prospector python[218853]: [2024-11-01 10:39:00,527: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'b88cbca1-c045-37a4-9e01-b8313e1f0599'} ticket:b8d9953c-5fe9-4097-8465-571b512874fb]
Nov 01 10:39:03 prospector python[218853]: [2024-11-01 10:39:03,263: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '6b72f8d4-01f6-3c8c-b2c3-259870eec9c8'} ticket:68eeb5b5-536f-4b29-8580-2ec0af0ddfe5]
Nov 01 10:39:05 prospector python[218853]: [2024-11-01 10:39:05,654: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'f5bed2a0-fe18-343e-bdad-a520f8d52075'} ticket:af847a19-d0dd-4fb5-9227-52cad897105d]
Nov 01 10:39:07 prospector python[218853]: [2024-11-01 10:39:07,914: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'b00a1226-ae71-3e2e-9272-7f06aef4dfc5'} ticket:264a4bd2-b4c1-4a8a-8480-1ef3a87dfd84]
Nov 01 10:39:10 prospector python[218853]: [2024-11-01 10:39:10,249: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '7d9ae773-5e9f-3736-a183-9eec81872697'} ticket:23fb9359-359f-4246-ba6d-24c29f468951]
Nov 01 10:39:12 prospector python[218853]: [2024-11-01 10:39:12,428: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '5f09210c-7f96-3e15-bd27-d722c411975b'} ticket:aeada689-2d77-4492-a161-4cee2d4eb31b]
Nov 01 10:39:14 prospector python[218853]: [2024-11-01 10:39:14,779: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '53f91d42-80fa-3af7-9feb-fd84c9e72980'} ticket:ca0cbdc1-f553-4b99-9953-d0f841b83578]
Nov 01 10:39:16 prospector python[218853]: [2024-11-01 10:39:16,959: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '9ecc62e5-5395-3efa-a8ab-ad14f5ec7c9d'} ticket:f5c55bf5-7d90-4f1b-8036-a1d4bc632f40]
Nov 01 10:39:19 prospector python[218853]: [2024-11-01 10:39:19,362: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'b8388725-1137-3fd6-baf1-60e936987ca2'} ticket:7a0fed80-c383-4a39-bcc2-10e9ba0a9b08]
Nov 01 10:39:21 prospector python[218853]: [2024-11-01 10:39:21,733: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '4eb66dd8-753f-3a85-8603-9dbcdbdaf65c'} ticket:61812823-4259-4d85-b364-2f228cacd05f]
Nov 01 10:39:23 prospector python[218853]: [2024-11-01 10:39:23,899: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '421e3368-3723-378e-8ed9-02be5a6abde7'} ticket:e8b725a3-ba18-49a4-8dfa-a5db2ac88ce4]
